In [6]:
import numpy as np

In [7]:
arr=np.array([6,5,4,2,7,8])
arr

array([6, 5, 4, 2, 7, 8])

In [8]:
np.max(arr)

8

In [9]:
np.min(arr)

2

In [12]:
np.argmin(arr) # position find min num in array 

3

In [13]:
np.argmax(arr) # position find max num in array

5

In [15]:
np.sqrt(arr) # squri rout find every num in array 

array([2.44948974, 2.23606798, 2.        , 1.41421356, 2.64575131,
       2.82842712])

In [16]:
arr

array([6, 5, 4, 2, 7, 8])

In [18]:
np.exp(arr) # mostly use nahi nahi hota

array([ 403.42879349,  148.4131591 ,   54.59815003,    7.3890561 ,
       1096.63315843, 2980.95798704])

In [22]:
np.sin(arr) # sin value return

array([-0.2794155 , -0.95892427, -0.7568025 ,  0.90929743,  0.6569866 ,
        0.98935825])

In [23]:
np.cos(arr) # cos value return

array([ 0.96017029,  0.28366219, -0.65364362, -0.41614684,  0.75390225,
       -0.14550003])

In [25]:
# this method is very important because
# ager we need to find 1 between 15 same space value we will use this function   
np.linspace(1,15,40)

array([ 1.        ,  1.35897436,  1.71794872,  2.07692308,  2.43589744,
        2.79487179,  3.15384615,  3.51282051,  3.87179487,  4.23076923,
        4.58974359,  4.94871795,  5.30769231,  5.66666667,  6.02564103,
        6.38461538,  6.74358974,  7.1025641 ,  7.46153846,  7.82051282,
        8.17948718,  8.53846154,  8.8974359 ,  9.25641026,  9.61538462,
        9.97435897, 10.33333333, 10.69230769, 11.05128205, 11.41025641,
       11.76923077, 12.12820513, 12.48717949, 12.84615385, 13.20512821,
       13.56410256, 13.92307692, 14.28205128, 14.64102564, 15.        ])

In [26]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

#  how to make boolen array

In [28]:
arr2=np.array([-1,2,0,5],dtype="bool")
arr2

array([ True,  True, False,  True])

In [38]:
lst=[5,4,7,8,9,6]
l=[]
for i in lst:
    print(i , end=" ")
    l=+i
    

5 4 7 8 9 6 