# Operators in numpy 
     + * % -

In [1]:
import numpy as np

In [2]:
arr=np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr * 4

array([ 4,  8, 12, 16, 20, 24, 28, 32])

In [4]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [5]:
arr //2

array([0, 1, 1, 2, 2, 3, 3, 4], dtype=int32)

In [6]:
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [7]:
arr % 3

array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int32)

In [8]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [9]:
arr=np.arange(1,10)
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr //2

array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4]], dtype=int32)

In [12]:
arr + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
1/0

ZeroDivisionError: division by zero

In [14]:
arr/0

c:\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

#  operations on two or more array
     array must be same size

In [15]:
arr1=np.arange(1,5)
arr1

array([1, 2, 3, 4])

In [16]:
arr2=np.arange(6,10)
arr2

array([6, 7, 8, 9])

In [17]:
arr1 + arr2 # *, % //, /

array([ 7,  9, 11, 13])

In [18]:
arr1 * arr1

array([ 1,  4,  9, 16])

In [19]:
arr3=np.arange(11,15)
arr3

array([11, 12, 13, 14])

In [20]:
arr1 * arr2 + arr3

array([17, 26, 37, 50])

In [34]:
# np.random.seed(123)
# matrix =np.random.randint(4,15,6).reshape(3,3)
# matrix2=np.random.randint(9,5,15).reshape(3,3)
mar=np.arange(2,11).reshape(3,3)
print(mar)
print()
mar2=np.arange(1,10).reshape(3,3)
print(mar)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [35]:
mar + mar2 # genarl format sum of matrix

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [38]:
# linear algbra
mar.dot(mar2) # school ma jas krta tha vo sum ha

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])