# create 2D array 

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,2,3,4],[4,5,7,8],[1,4,7,8]])
matrix

array([[1, 2, 3, 4],
       [4, 5, 7, 8],
       [1, 4, 7, 8]])

# indexing using double bracket notation

In [3]:
matrix[0][1]

2

In [4]:
matrix[2][3]

8

# indexing using single braket notation(Recommended)

In [5]:
matrix

array([[1, 2, 3, 4],
       [4, 5, 7, 8],
       [1, 4, 7, 8]])

In [6]:
matrix[0,1]

2

In [7]:
matrix[1,1]

5

In [8]:
matrix[2,3]

8

#  slicing using single bracket notation

In [9]:
matrix

array([[1, 2, 3, 4],
       [4, 5, 7, 8],
       [1, 4, 7, 8]])

In [10]:
# [[1,2],
# [4,5]]
matrix[:2, :2]

array([[1, 2],
       [4, 5]])

In [11]:
# 5,7
# 4,7
print(matrix[1:3,1:3])
print()
print(matrix[1:,1::1])

[[5 7]
 [4 7]]

[[5 7 8]
 [4 7 8]]


In [12]:
matrix

array([[1, 2, 3, 4],
       [4, 5, 7, 8],
       [1, 4, 7, 8]])

In [13]:
matrix[1:, 1:]

array([[5, 7, 8],
       [4, 7, 8]])

In [14]:
np.random.seed(123)
martix2 = np.random.randint(1, 101, 25).reshape(5,5)
martix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [15]:
martix2[1:4,1:4] # row:row, column:column

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])

In [16]:
martix2[0:5, 1:4]

array([[93, 99, 18],
       [87, 98, 97],
       [33, 47, 97],
       [79, 37, 97],
       [50, 56, 68]])

In [17]:
martix2

array([[67, 93, 99, 18, 84],
       [58, 87, 98, 97, 48],
       [74, 33, 47, 97, 26],
       [84, 79, 37, 97, 81],
       [69, 50, 56, 68,  3]])

In [18]:
martix2[3:5, 3:5]

array([[97, 81],
       [68,  3]])

In [19]:
martix2[2:5,2:5]

array([[47, 97, 26],
       [37, 97, 81],
       [56, 68,  3]])

In [20]:
martix2[1:4,1:4]

array([[87, 98, 97],
       [33, 47, 97],
       [79, 37, 97]])