In [1]:
import numpy as np

# view 

In [2]:
arr=np.array([4,5,7,8,93,2,45])

In [3]:
sliced_array = arr[2:5]
sliced_array

array([ 7,  8, 93])

In [4]:
sliced_array[:]=0
sliced_array

array([0, 0, 0])

In [5]:
arr

array([ 4,  5,  0,  0,  0,  2, 45])

# copy 

In [6]:
arr2= np.array([1,4,5,7,9,5,1,3])
arr2

array([1, 4, 5, 7, 9, 5, 1, 3])

In [7]:
slc=arr2[2:5].copy()
slc

array([5, 7, 9])

In [8]:
slc[:]=0
slc

array([0, 0, 0])

In [9]:
arr2

array([1, 4, 5, 7, 9, 5, 1, 3])

In [13]:
slc[:]=0
slc

array([0, 0, 0])

# Condition selection


In [15]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
greater=arr>6
greater

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [19]:
arr[greater]

array([ 7,  8,  9, 10])

In [20]:
arr[arr<6]

array([1, 2, 3, 4, 5])

In [27]:
arr[arr%2==0]
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [29]:
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [31]:
arr[arr==7]

array([7])

0