In [1]:
import numpy as np
# reshape it meain one d into 2D and 2D into one D

In [2]:
arr= np.random.randint(1,200,30)
arr

array([109, 184,  17, 137,  42, 176, 139,  80,  56,  48, 187,  22, 164,
        53,  42,  14,  37,  31, 162, 135, 167,  48, 131,  92, 130, 185,
         2, 122,  62, 184])

In [3]:
arr.ndim

1

In [4]:
arr.shape

(30,)

In [5]:
arr2= np.random.randint(1,200,30)  # 1D to 2D convert
arr2= arr2.reshape(2,15)
arr2

array([[173,  70, 189,  73,  13, 103, 160,  40, 165,  30,  79, 126, 131,
         74, 112],
       [  6, 199, 130, 167,  87,  43,  63, 160,  71,  12,  30,   7, 103,
         72,  33]])

In [6]:
arr.ndim

1

In [7]:
arr.shape

(30,)

In [8]:
arr1= np.random.randint(1,200,30) # 2D to 1D convert
arr1= arr1.reshape(30)
arr1

array([181,  97,  70,  44, 158, 165,  16, 168, 154,  45,  26,  98,  67,
        52, 174,  46,  26,  11,  77, 122,  84,  19, 154,   4,  40, 153,
       165, 116, 165,  83])

In [9]:
arr1.ndim

1

In [10]:
arr1.shape

(30,)

In [11]:
arr= np.random.randint(1,200,30)
arr= arr.reshape(6,5)
arr

array([[ 73, 136, 156, 190,  65],
       [124, 161,  18, 151, 182],
       [ 12,  34, 107,  74, 129],
       [ 95,  36,  82, 181,  19],
       [ 48,  46,  93,  94,  84],
       [119,  99,  66, 108,  21]])

In [12]:
arr.shape

(6, 5)

In [13]:
arr.ndim

2

In [14]:
arr3= np.random.randint(1,200,30) # 2D to 3D
arr3= arr3.reshape(2,3,5)
arr3

array([[[122, 108,   7,  36, 167],
        [ 36,  23,  83,  25,  84],
        [ 39,  34,  76, 189, 107]],

       [[ 29, 165, 154, 137, 156],
        [170,  63,  67, 103, 176],
        [ 10, 123,   9, 123, 131]]])

In [22]:
np.random.seed(12)# use of 'seed' fix random noumber dont change
arr=np.random.randint(1,101,10) # ever time same numer generate
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [23]:
# count number of element in array
arr.size

10

#  indexing and slicing in numpy array

In [24]:
arr=np.array([2,3,4,5,6,7,8])
arr

array([2, 3, 4, 5, 6, 7, 8])

In [25]:
arr[2]

4

In [26]:
arr[0]

2

In [27]:
arr[-1]

8

In [28]:
arr[-5]

4

In [30]:
# slicing
arr

array([2, 3, 4, 5, 6, 7, 8])

In [32]:
arr[0:3]

array([2, 3, 4])

In [33]:
arr[1:5:2]

array([3, 5])

In [34]:
arr[1:]

array([3, 4, 5, 6, 7, 8])

In [35]:
arr[:4]

array([2, 3, 4, 5])

In [36]:
arr[-3:]

array([6, 7, 8])