In [1]:
import numpy as np

# numpy array
* it is python libarary designed for scientic computation.
* NumPy arrays are the main way to use Numpy Library.
* Multi dimensional arrays using numpy.
* It is really fast compare to ordinary  python lists.
* It is fost because it has binding with C Language.
#### 1-d array vector
#### 2d array matrix
#### n-d array tensor

In [2]:
# One D array
lst=[1,2,3,4]
lst=np.array(lst)
lst

array([1, 2, 3, 4])

In [3]:
# 2D array
nums=[[1,2,3],[4,5,6],[7,5,4]]
nums=np.array(nums)
nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 5, 4]])

In [4]:
# 3D array
n=[[[1,2,3],[4,5,6],[7,5,4]],[[12,13,14],[15,16,17],[11,22,33]]]
n=np.array(n)
n

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  5,  4]],

       [[12, 13, 14],
        [15, 16, 17],
        [11, 22, 33]]])

In [5]:
n.ndim # use type of array like 3d and 2d we can chack

3

In [6]:
n.shape # show will be row and column and matrix

(2, 3, 3)

In [10]:
nums.ndim # show 2d array 
nums.shape # 3 columns and 3 row in 2d array

(3, 3)

# we can store one type of data in numpy array 

In [14]:
# How to create numpy array using numpy functions.

# zeros,  ones,  eye,  diag,  randint,  rand,  randn

In [15]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [17]:
arr1=np.zeros((2,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr1=np.ones(5)
arr1

array([1., 1., 1., 1., 1.])

In [20]:
arr1=np.ones((2,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
arr1=np.eye(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
arr2=np.eye(2,3) # 2 row and 3 column and dignal True
arr2

array([[1., 0., 0.],
       [0., 1., 0.]])

In [27]:
arr3=np.diag([1,2,3,4])
arr3

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
arr3=np.diag([1,2,3,4])
np.diag(arr3)

array([1, 2, 3, 4])

In [33]:
arr_rand= np.random.randint(1,15,4) # low, High, how many u want. 
arr_rand

array([10, 13, 10,  7])

In [35]:
# rand
# 0 to 1 kan midel ke value day ga jo randomly ho gya
rand_arr = np.random.rand(4) 
rand_arr

array([0.16675915, 0.19315337, 0.27410585, 0.79864904])

In [36]:
# ya random number day ga jis ma 4 row and 2 column 
rand_arr = np.random.rand(4,2)
rand_arr

array([[0.24871622, 0.79633876],
       [0.95363503, 0.85017149],
       [0.57373725, 0.53339089],
       [0.98210265, 0.78643295]])

In [37]:
# randn
# es ma negitive no. be ho gya
rand_arr = np.random.randn(4)
rand_arr

array([ 1.33256168, -0.63929045,  0.59348511, -0.24971493])

In [41]:
# we can find the mean
rand_arr = np.random.randn(8)
np.mean(rand_arr)

-0.012145422869677916

In [5]:
b=""
print(type(b),id(b))
b="hii"
print(id(b))

<class 'str'> 13748608
98376192


In [14]:
a=(1,2,3)
print(id(a))
a=(4,5,6)

7945072


In [15]:
print(id(a))

7944632


In [18]:
a=4
print(id(a),a)
a=5

1841259744 4


In [19]:

print(id(a),a)

1841259760 5


In [20]:
None==None

True

In [21]:
st=['H','E','L','L','o']
len(st)

5

In [23]:
print(len(set(st)))

4


In [24]:
handle='TheCodanV'
msg=[]
if 'Cod' in handle:
    msg+= ['Design', 'Code']
elif 'an' in handle:
    msg.append("Analyse")
if "V" in handle:
    msg.append('Visualize')
    
print(msg)

['Design', 'Code', 'Visualize']


In [33]:
for i in range(1,20,2):
    print(("*"*i).center(20))

         *          
        ***         
       *****        
      *******       
     *********      
    ***********     
   *************    
  ***************   
 *****************  
******************* 
